version: "3"
networks:
  iresponse:

services:
  nginx:
    image: library/nginx:stable-alpine
    container_name: LAMP-nginx
    volumes:
      - ./src/app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8060:80"
    depends_on:
      - php
      - mysql
    networks:
      - iresponse

  mysql:
    image: library/mysql:5.7.22
    container_name: LAMP-mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - iresponse
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: mysql
      SERVICE_TAG: dev

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: LAMP-php
    volumes:
      - ./src/app:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - iresponse
